---
root: true
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: "module"
  project: "./tsconfig.json"
plugins:
  - "@typescript-eslint"
  - "prettier"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - prettier
env:
  node: true
settings:
  react:
    version: detect
rules:
  "prettier/prettier": "error"